name: Collect dsBaseClient test suite results

on:
  workflow_run:
    workflows: ["dsBaseClient tests' suite"]
    types:
      - completed

jobs:
  collect-results:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # we need to push into testStatus
      
    steps:
      - name: Checkout testStatus
        uses: actions/checkout@v4
        with:
          path: testStatus

      - name: Download dsBaseClient artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: dsBaseClient tests' suite
          run_id: ${{ github.event.workflow_run.id }}
          repo: ${{ github.event.workflow_run.repository.full_name }}
          name: dsbaseclient-logs
          path: logs-download

      - name: Commit logs into repo
        run: |
          cd testStatus
          branch="${{ github.event.workflow_run.head_branch }}"
          runid="${{ github.event.workflow_run.id }}"
          
          mkdir -p logs/dsBaseClient/${branch}/${runid}
          mkdir -p docs/dsBaseClient/${branch}/${runid}
          mkdir -p docs/dsBaseClient/${branch}/${runid}/latest
          
          # clear the latest directory
          rm -rf docs/dsBaseClient/${branch}/${runid}/latest/*
          
          # copy new contents
          cp -r ../logs-download/logs/dsBaseClient/${branch}/${runid}/* logs/dsBaseClient/${branch}/${runid}/
          cp -r ../logs-download/docs/dsBaseClient/${branch}/${runid}/* docs/dsBaseClient/${branch}/${runid}/
          cp -r ../logs-download/docs/dsBaseClient/${branch}/latest/* docs/dsBaseClient/${branch}/latest/

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Results from workflow ${runid}" || echo "No changes"
          git push
